### ISSUE TITLE
RFC Consider just using reStructured Text for hand written docs

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/flucoma-docs#29]
At the moment we have a slightly bizarre system where the hand-written portion of the documentation is a YAML file, certain portions of which can contain rst markup to enable inline formatting in the generated reference for whatever host. Like all the best decisions, it came from successive needs to solve the problem in front of us quickly, but isn't exactly friendly. 

* Two formats in one file is confusing at the best of times 
* Both YAML and rst treat white space as semantically meaningful, but in different ways. This makes mistakes easy to produce, and not always easy to catch or diagnose. 

On the upside, YAML is a good match for the kind of structured data we want to present (i.e. about what controls and messages a Client exposes). The general use case for rst is more general, so specifying how we would want to write such structures in a way that is robust and checkable requires some thought. 

This change shouldn't have any effect on the overall documentation workflow, save for changing the format that humans have to work with. The generating stage should still work in the same way (although this *would* open the door for a future migration to sphinx if we wanted)

The obvious thing to do is follow what `docutils` and `sphinx` do for documenting code in various languages, and use the same sorts of rst entities to do the same sorts of work. Concretely, let's say we have some Client whose YAML currently looks like
```yaml
digest: Open a wormhole to the other side of the universe
see-also: Singularity 
description: Wormhole is a way of tearing the fabric of space-time
parameters:
  name:
    description: The name of the Wormhole. This is unique between all Wormhole.
messages:
  collapse: 
    description: collapse the wormhole, possibly with *devastating* effects
    args: 
      - name: quantum 
      - description: something quantum 
```

Man, that's worse than I remember 😆 I think the rst would look something like: 

```reStructuredText 
:digest: Open a wormhole to the other side of the universe
:see-also: Singularity 
:description: Wormhole is a way of tearing the fabric of space-time

.. parameter:: name

   The name of the Wormhole. This is unique between all Wormhole.

.. message:: quantum 

   collapse the wormhole, possibly with *devastating* effects

   :arg quantum: something quantum 

```

Which is no shorter but perhaps clearer? The slightly weird syntax
```reStructuredText
.. <something>::
```

is what's called a `directive` in rst, and seems to be the canonical way to represent some structured entity (see how the `message` directive above has a an inset `:arg <name>:` field`)   

(note that `parameter`s are about to be re-dubbed `control`s in a future Client API re-do, so an actual doc format would probably anticipate that).

@jamesb93 @tremblap @tedmoore any thoughts about the relative ickiness of these ways of spelling docs for Clients?
